### ISSUE TITLE
Add Authorization in API

### ISSUE THREAD

**Issue by DK-Khambhadiya** [DK-Khambhadiya/book-manager#1]
- Add Authentication Support
- Add Middleware for Authorization

**Comment by bloodmonk7** [comment]
I can do this using nextAuth will it be good?

**Comment by DK-Khambhadiya** [comment]
> I can do this using nextAuth will it be good?

I Want Custom Authentication for now. May be using JWT.

**Comment by bloodmonk7** [comment]
I think we should connect for this one and talk more about it to get a better idea of what you need... I will surely be up for help!

**Comment by DugarRishab** [comment]
Hey @DK-Khambhadiya I can make a authorization middleware for you API. I too have a similar Project called "Template".

**Comment by DK-Khambhadiya** [comment]
> I think we should connect for this one and talk more about it to get a better idea of what you need... I will surely be up for help!

It seems you're spamming over Issue so you're rejected for my projects which are open for `hacktoberfest`.

**Comment by DugarRishab** [comment]
Hey @DK-Khambhadiya, it seems like you are not convinced. Please check out my repo: https://github.com/DugarRishab/Track-it-API 
In this repo (and many others), I have implemented Authorization using JWT cookies and Bearer Tokens.

**Comment by laurisseau** [comment]
Hi, can i work on this?

**Comment by DK-Khambhadiya** [comment]
Hey Guys, You all are good to know. Please collaborate with each other for the same.

**Comment by HackvistCharm** [comment]
Hii @DK-Khambhadiya , I would like to work on this issue. can you please assign it to me?
