### ISSUE TITLE
GitHub Workflow Automation

### ISSUE THREAD

**Issue by DK-Khambhadiya** [DK-Khambhadiya/Book-Manager#2]
- Add GitHub issue templates 
- Add GitHub pull request workflows

**Comment by SupOrg** [comment]
@DK-Khambhadiya can you please assign me this task? :)

**Comment by Disha-Bhuva** [comment]
Hey I would like to work on the issue I have good knowledge of github workflows could you please assign me the issue

**Comment by DK-Khambhadiya** [comment]
You all are good to go ✨
